#!/bin/bash
set -m
if [ "$#" != 0 ]; then
	builtin cd "$@";
	return
fi
while true; do
	lsd=$(echo ".." && ls -p) # | grep '/$' | sed 's;/$;;')
	dir="$(printf '%s\n' "${lsd[@]}" |
		fzf --reverse --preview '
			__cd_nxt="$(echo {})";
			__cd_path="$(echo $(pwd)/${__cd_nxt} | sed "s;//;/;")";
			echo $__cd_path;
			echo;
			if [ "${__cd_path: -1}" = "/" ] || [ "${__cd_path}" = "$(pwd)/.." ];
			then
				ls -p --color=always "${__cd_path}"
			else
				__ext="${__cd_path: -4}"
				case "${__ext}" in
					".jpg" | ".png" | ".gif")
						chafa "${__cd_path}"
						;;
					*)
						bat "${__cd_path}" --color=always;
						;;
				esac
			fi
			')"
			if [ ${#dir} = 0 ];
			then
				break #exit 0	
			fi
			if [ "${dir: -1}" = "/" ] || [ "${dir}" = ".." ];
			then
				builtin cd "$dir" &> /dev/null
			else
				ext="${dir: -4}"
				case "$ext" in
					".jpg" | ".png" | ".gif")
						feh "$dir"
						;;
					*)
						 ${EDITOR:-${VISUAL:-vi}} "$dir"
						;;
				esac

			fi
		done
